reference_genome: /rgs01/project_space/tsaigrp/Genomics/common/genomes/hg38/hg38_chroms_only.fa
blacklist: /rgs01/project_space/tsaigrp/Genomics/common/genomes/hg38/hg38-blacklist.v2.bed.gz
# if not specified, default is NGG
PAM: NGG

# output folder directory (absolute or relative path), if not specified, default is current dir
analysis_folder: /rgs01/project_space/tsaigrp/Genomics/common/projects/CHANGE_seq/CHANGE_seq_05022021/test/


# PATH to analysis tools
# If not specified, default is just the tool name, i.e., accessible in the $PATH
bwa: bwa
samtools: samtools
trim_galore: trim_galore
cutadapt: cutadapt
bedtools: bedtools
Rscript: /home/yli11/.conda/envs/captureC/bin/Rscript
# guideseq

window_size: 25
max_score: 7
on_target_reference_sequence: GTCCCTAGTGGCCCCACTGTAGG
# consolidation

CONSOLIDATE_MIN_QUAL: 15
CONSOLIDATE_MIN_FREQ: 0.9

# parallel
njobs: 6


# read filter
mapq_threshold: 50


# dsODN_primer
i7+: ATACCGTTATTAACATATGACA
i7-: GTTTAATTGAGTTGTCATATGTTAATAAC
dsODN_primer: GTTTAATTGAGTTGTCATATGTTAATAACGGTAT # primer sequence that matches i7- 
dsODN_primer_revcomp: ATACCGTTATTAACATATGACAACTCAATTAAAC # primer sequence that matches i7+ 
control_primer: AGATGCCTTTGGGGATACTCC

# primer sequence matching
# example, <= match_distance is a match
# >= mispriming_distance is a mispriming
# all distance here is edit distance
i7+_match_distance: 2
i7-_match_distance: 3
control_primer_match_distance: 2
i7+_mispriming_distance: 3
i7-_mispriming_distance: 2
i7+_mispriming_length: 12
i7-_mispriming_length: 5

samples:
    AAVS1_site_2_d3:
        target: GTCCCTAGTGGCCCCACTGTNGG
        read1: CRL2619_S9_R1_100.fastq.gz
        read2: CRL2619_S9_R2_100.fastq.gz
        index1: CRL2619_S9_I1_100.fastq.gz
        index2: CRL2619_S9_I2_100.fastq.gz
        controlread1: CRL2613_S3_R1_100.fastq.gz
        controlread2: CRL2613_S3_R2_100.fastq.gz
        controlindex1: CRL2613_S3_I1_100.fastq.gz
        controlindex2: CRL2613_S3_I2_100.fastq.gz
        description:  AAVS1_site_2_d3


